-- 코드를 입력하세요
SELECT USB.TITLE, USB.BOARD_ID, UGR.REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS, DATE_FORMAT(UGR.CREATED_DATE, "%Y-%m-%d")
FROM USED_GOODS_BOARD USB join USED_GOODS_REPLY UGR on USB.BOARD_ID = UGR.BOARD_ID
WHERE DATE_FORMAT(USB.CREATED_DATE, "%Y-%m") = "2022-10"
ORDER BY UGR.CREATED_DATE, USB.TITLE
;