-- 코드를 입력하세요
SELECT a.BOOK_ID, b.AUTHOR_NAME, DATE_FORMAT(a.PUBLISHED_DATE,"%Y-%m-%d") AS PUBLISHED_DATE
FROM BOOK a join AUTHOR b on a.AUTHOR_ID = b.AUTHOR_ID
WHERE a.CATEGORY like '경제'
ORDER BY a.PUBLISHED_DATE